GET https://radiant-headland-90049.herokuapp.com/api/v1/flowers

###
POST https://radiant-headland-90049.herokuapp.com/api/v1/flowers
Content-Type: application/json

{
  "sepalLength": 100,
  "color": 0,
  "price": 100,
  "flowerType": 2,
  "type": 2
}